# Generated by Django 4.1.7 on 2023-05-04 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_entry_deep_entry_created_at_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='NLPRequest',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('modified_at', models.DateTimeField(auto_now=True)),
                        ('client_id', models.CharField(max_length=50)),
                        ('status', models.IntegerField(choices=[(1, 'Initiated'), (2, 'Success'), (3, 'Failed'), (4, 'Process Input Url Failed')], default=1)),
                        ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                        ('result_s3_link', models.TextField(blank=True, null=True)),
                        ('type', models.CharField(choices=[('ngrams', 'Ngrams'), ('topicmodel', 'Topicmodel'), ('summarization', 'Summarization'), ('geolocation', 'Geolocation')], max_length=20)),
                        ('request_params', models.JSONField(blank=True, null=True)),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'event_status_tracker',
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='FailedCallback',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('modified_at', models.DateTimeField(auto_now=True)),
                        ('request_unique_id', models.UUIDField(unique=True)),
                        ('retries_count', models.PositiveIntegerField(default=0)),
                        ('last_retried_at', models.DateTimeField(null=True)),
                        ('status', models.PositiveIntegerField(choices=[(0, 'Success'), (1, 'Retries maxed out'), (2, 'Failed'), (3, 'Retrying')], default=3)),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'failed_callback_tracker',
                    },
                ),
            ],
            database_operations=[],
        )
    ]
